// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPgIXGFR7QKqHK88ngvgJXvU6y7o2rRyo',
    appId: '1:289978390831:web:75e8302ee47409f38ca9da',
    messagingSenderId: '289978390831',
    projectId: 'finalme-70f25',
    authDomain: 'finalme-70f25.firebaseapp.com',
    storageBucket: 'finalme-70f25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACmnnGcwguVA41Xrv7EKQeKDiRyJgKCPg',
    appId: '1:289978390831:android:fd2da0e853fd17728ca9da',
    messagingSenderId: '289978390831',
    projectId: 'finalme-70f25',
    storageBucket: 'finalme-70f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBsTtZUtMBBwQckWD49Lw2_rlQ3e7pz4',
    appId: '1:289978390831:ios:9e56b38aad4cedd88ca9da',
    messagingSenderId: '289978390831',
    projectId: 'finalme-70f25',
    storageBucket: 'finalme-70f25.appspot.com',
    iosClientId:
        '289978390831-e6802jg49luffmiq91mmprv0moi7p893.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBsTtZUtMBBwQckWD49Lw2_rlQ3e7pz4',
    appId: '1:289978390831:ios:9e56b38aad4cedd88ca9da',
    messagingSenderId: '289978390831',
    projectId: 'finalme-70f25',
    storageBucket: 'finalme-70f25.appspot.com',
    iosClientId:
        '289978390831-e6802jg49luffmiq91mmprv0moi7p893.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
